info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Index
  /user/getUserData:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
      - GetUserData
swagger: "2.0"
